fix(style): address issue with duplicate dividers #18
AlaskaAirlines/auro-menu pull request #19
Opened 2021-08-20 21:02 UTC by ftaylor-alaska

# Alaska Airlines Pull Request

Cleans up the way dividers are shown for sub-menu options

**Fixes:** #18 

## Summary:

## Type of change:

- [x] Revision of an existing capability

## Checklist:

- [ ] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2021-08-20 22:33 UTC, blackfalcon requested changes
Update commit, try, 

```
fix(style): address issue with duplicate dividers #18
```

2021-08-23 21:50 UTC, blackfalcon requested changes

2021-08-23 21:50 UTC, blackfalcon commented on src/auro-sub-menu.js
> +  firstUpdated() {
I feel like this is a UI issue. Can this not be solved with the CSS?

2021-08-23 23:05 UTC, ftaylor-alaska commented on src/auro-sub-menu.js
> +  firstUpdated() {
To re-iterate what this bug is: When a auro-sub-menu is first, last, or following another auro-sub-menu, we have an unwanted divider. These dividers aren't borders on the auro-sub-menu, but instead are divs of their own.

![image](https://user-images.githubusercontent.com/51933786/130529699-15986513-f24a-4ba0-a3f5-d68008fc94a5.png)

Part of the design spec is to have dividers above/below a group of menu options. This divider can't be a border on this parent element because it must be less wide than the containing items. Therefore, there is a separate div (.divider) within the parent (auro-sub-menu). Could you explain how we might conditionally set these inner dividers based on the location of the parent div (auro-sub-menu). I'm trying to think of a clever way to use the pseudo attributes such as first-child etc. to come up with this. In the future it looks like a selector :has could be used but this is not yet available.

2021-09-07 21:36 UTC, blackfalcon commented on src/auro-sub-menu.js
> +  firstUpdated() {
Will allow this to merge for now. New issue created for post-merge refactor.

2021-09-07 21:36 UTC, merged

2021-09-09 18:19 UTC, blackfalcon commented
:tada: This PR is included in version 1.2.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurolabs/auro-menu/v/1.2.2)
- [GitHub release](https://github.com/AlaskaAirlines/auro-menu/releases/tag/v1.2.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: