Refactor in prep for release
AlaskaAirlines/auro-menu pull request #58
Opened 2022-01-12 21:18 UTC by blackfalcon

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Resolves:** See 'linked issues'

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

This PR will address a number of issues within the scope of preparing this repo for release. See individual commits for additional details. 

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2022-01-13 17:18 UTC, jason-capsule42 commented
The branch fails to run for me.

`[0] TypeError: Cannot read property 'nodes' of undefined
[0]     at l (/Users/jasonbaker/Development/AlaskaAir/AlaskaAirlines/auro-menu/node_modules/postcss-custom-properties/dist/index.cjs:1:644)
[0]     at Object.prepare (/Users/jasonbaker/Development/AlaskaAir/AlaskaAirlines/auro-menu/node_modules/postcss-custom-properties/dist/index.cjs:1:5256)
[0]     at /Users/jasonbaker/Development/AlaskaAir/AlaskaAirlines/auro-menu/node_modules/postcss/lib/lazy-result.js:149:39
[0]     at Array.map (<anonymous>)
[0]     at new LazyResult (/Users/jasonbaker/Development/AlaskaAir/AlaskaAirlines/auro-menu/node_modules/postcss/lib/lazy-result.js:147:43)
[0]     at Processor.process (/Users/jasonbaker/Development/AlaskaAir/AlaskaAirlines/auro-menu/node_modules/postcss/lib/processor.js:28:14)
[0]     at /Users/jasonbaker/Development/AlaskaAir/AlaskaAirlines/auro-menu/scripts/postCss.js:65:6
[0]     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:71:3)
[0] npm notice 
[0] npm notice New major version of npm available! 7.24.2 -> 8.3.0
[0] npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.3.0>
npm notice Run `npm install -g npm@8.3.0` to update!
[0] npm notice 
[0] ERROR: "postCss:component" exited with 1.
[0] npm notice 
[0] npm notice New major version of npm available! 7.24.2 -> 8.3.0
[0] npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.3.0>
[0] npm notice Run `npm install -g npm@8.3.0` to update!
[0] npm notice 
[0] [nodemon] app crashed - waiting for file changes before starting...`

2022-01-13 17:24 UTC, jason-capsule42 requested changes

2022-01-13 17:24 UTC, jason-capsule42 commented on src/auro-menu-option.js
>   * @attr {Number} tabIndex - Will be either -1 or 0 depending on if auro-menu is currently visible or not.
This was removed below but the description is still here causing it to show up in the API doc.
```suggestion
```

2022-01-13 17:24 UTC, jason-capsule42 commented on src/auro-menu-option.js
>   * @attr {Boolean} isHidden - If the auro-menu-option is currently visible or not, perhaps because auro-dropdown is controlling whether or not auro-menu is visible or hidden.
This should be removed if we aren't using `isHidden` any more.
```suggestion
```

2022-01-13 17:24 UTC, jason-capsule42 commented on src/auro-menu-option.js
>        hasFocus:         { type: Boolean },
Regarding all properties declared except `selected`

I don't see these properties getting used anywhere. We set and remove it and it says it's to control styles but there doesn't appear to be anything in the code that makes use of the it.

Looks like it should be removed.

2022-01-13 17:24 UTC, jason-capsule42 commented on src/auro-menu.js
> +        const parentIndexSelectedOption = this.indexSelectedOption;
I don't understand this change. The if wrapper on this is looking to see if the parent element has `indexSelectedOption` so that we can apply that value if so. This change would make it so that even if the parent has a declared `indexSelectedOpton` we aren't using it.

2022-01-18 20:08 UTC, blackfalcon commented on src/auro-menu.js
> +        const parentIndexSelectedOption = this.indexSelectedOption;
Got it... I understand what this is doing now. This looks to see of `indexSelectedOption` is on a wrapping undefined parent? E.g. 

```html
  <auro-thing indexSelectedOption="2">
    <auro-menu id="auroMenu2" icon>
      <auro-menu-option data-value="Stops">Stops</auro-menu-option>
      <auro-menu-option disabled data-value="Price">(disabled) Price</auro-menu-option>
      <auro-menu-option data-value="Duration">Duration</auro-menu-option>
      <auro-menu-option data-value="Departure">Departure</auro-menu-option>
      <auro-menu-option data-value="Arrival">Arrival</auro-menu-option>
    </auro-menu>
  </auro-thing>
```

**Question:** Why would we support this? If the API is defined that `indexSelectedOption` is to be on `auro-menu` why would this be needed?

2022-01-18 20:09 UTC, blackfalcon commented
> The branch fails to run for me.
> 
> `[0] TypeError: Cannot read property 'nodes' of undefined [0] at l ...`

Try running `npm ci` and be sure you are on node 16.x.

2022-01-18 20:10 UTC, blackfalcon commented on src/auro-menu-option.js
>   * @attr {Number} tabIndex - Will be either -1 or 0 depending on if auro-menu is currently visible or not.
It has been removed.

2022-01-18 20:10 UTC, blackfalcon commented on src/auro-menu-option.js
>   * @attr {Boolean} isHidden - If the auro-menu-option is currently visible or not, perhaps because auro-dropdown is controlling whether or not auro-menu is visible or hidden.
It has been removed

2022-01-18 20:25 UTC, blackfalcon commented on src/auro-menu-option.js
>        hasFocus:         { type: Boolean },
removed

2022-01-18 20:29 UTC, blackfalcon commented on src/auro-menu.js
> +        const parentIndexSelectedOption = this.indexSelectedOption;
For the sake of this PR, the functionality stands. I created a new issue https://github.com/AlaskaAirlines/auro-menu/issues/67 to support the conversation of refactoring or removal of this code.

2022-01-18 21:51 UTC, jason-capsule42 requested changes

2022-01-18 21:51 UTC, jason-capsule42 commented on src/style-sub-menu.scss
>  .subMenu {
Not sure where to insert this exactly but the current icon styles are broken for nested menu options when putting the icon attribute on a menu that has a submenu.

2022-01-18 21:51 UTC, jason-capsule42 commented on src/auro-menu.js
>        this.options[iter].setAttribute('tabindex', '0');
This isn't handling disabled menu items. Anything disabled can still be focused using tab and arrow keys.

2022-01-18 21:51 UTC, jason-capsule42 commented on docs/api.md
> +| `hideTop`    | `hideTop`    | `Boolean` | Removes hr line from top of sub-menu     |
Seems like these properties are a little unnecessary to me. If I understand correctly the figma doesn't seem to imply that all submenus default to having a divider on the top and bottom.

I think these should be removed the implementer should just add the dividers as needed. 

If design wants to keep the dividers as the default we should know if the there is ever a scenario where they would only use the top or bottom. Seems like if they are there then it's going to be both. So we might as well use a single attribute for submenu divider to simplify this.

2022-01-18 21:58 UTC, blackfalcon commented on src/auro-menu.js
>        this.options[iter].setAttribute('tabindex', '0');
Will be addressed with https://github.com/AlaskaAirlines/auro-menu/issues/55

2022-01-18 21:58 UTC, blackfalcon commented on docs/api.md
> +| `hideTop`    | `hideTop`    | `Boolean` | Removes hr line from top of sub-menu     |
I suspected that, was going to address that with https://github.com/AlaskaAirlines/auro-menu/issues/54

2022-01-18 22:00 UTC, blackfalcon commented on src/style-sub-menu.scss
>  .subMenu {
I was going to come back to that. https://github.com/AlaskaAirlines/auro-menu/issues/54

2022-01-18 22:02 UTC, jason-capsule42 commented
> > The branch fails to run for me.
> > `[0] TypeError: Cannot read property 'nodes' of undefined [0] at l ...`
> 
> Try running `npm ci` and be sure you are on node 16.x.

Turns out this came from having .map files left behind from doing a build on a previous version of the generator.

2022-01-18 22:08 UTC, jason-capsule42 approved these changes

2022-01-18 22:55 UTC, merged