Reduce scope
AlaskaAirlines/auro-menu pull request #71
Opened 2022-01-20 20:37 UTC by blackfalcon

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Resolves:** #69 

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

The scope of this commit is to remove code that is no longer in scope of this release. Being an individual commit, we can go back and return code as needed as we continue to support these features moving forward.

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2022-01-20 23:56 UTC, jason-capsule42 commented
The basic example imported in the readme.md needs to be updated to match the current API.

2022-01-21 00:07 UTC, jason-capsule42 commented
Something I find odd with the current implementation is that the select color styles are applied on `mousedown` but the checkmark doesn't show up until `mouseup`. We should aim to have both occur on `mousedown` I think.

2022-01-21 00:08 UTC, jason-capsule42 requested changes
Readme API example doesn't match current functionality.

2022-01-21 05:44 UTC, blackfalcon commented
> Something I find odd with the current implementation is that the select color styles are applied on `mousedown` but the checkmark doesn't show up until `mouseup`. We should aim to have both occur on `mousedown` I think.

The functionality that you are pointing out, as it turns out is expected behavior. 

> An element receives a click event when a pointing device button (such as a mouse's primary mouse button) is both **pressed and released** while the pointer is located inside the element.

While I agree that this is a slightly weird experience, an update supports both the `click` and a `mousedown` event.

2022-01-21 05:49 UTC, blackfalcon commented
@jason-capsule42 see last two commits, these address the issues you raised.

2022-01-21 16:46 UTC, jason-capsule42 requested changes
Small note about the `selected` property, I think that should be private?

Otherwise this looks great.

2022-01-21 16:46 UTC, jason-capsule42 commented on docs/api.md
> +| `selected` | `selected` | `boolean` |                                                  |
This should be private shouldn't it?

2022-01-21 17:37 UTC, blackfalcon commented on docs/api.md
> +| `selected` | `selected` | `boolean` |                                                  |
This is being addressed in https://github.com/AlaskaAirlines/auro-menu/issues/48

2022-01-21 17:41 UTC, jason-capsule42 approved these changes

2022-01-21 17:43 UTC, merged