feat(API): add optionSelected property
AlaskaAirlines/auro-menu pull request #94
Opened 2022-03-04 21:12 UTC by jason-capsule42

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #92

## Summary:

This change adds a new `optionSelected` property. This will be used as a quick efficient means to get all data associated with the currently selected menu option.

Currently `auro-select` will loop through all menu-options looking for one that matches the saved value and then fetch the data it needs off of that object. With this change select will simply be able to do `auro-menu.optionSelected.innerText` or any other normal query directly.

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2022-03-08 17:55 UTC, blackfalcon requested changes
I guess I wasn't 100% understanding of the exit criteria. When it was explained that an object would be returned, I assumed that this was an object of data. When I a looking at the return of this object, I am given the HTML for the returned element. Is that correct? 

<img width="946" alt="Screen Shot 2022-03-08 at 9 50 32 AM" src="https://user-images.githubusercontent.com/181089/157296626-02212648-e135-4e58-ad85-48e186954a75.png">

I feel that there should be additional documentation to support this in the demo or the API doc.

2022-03-08 17:55 UTC, blackfalcon commented on src/auro-menu.js
> +    this.setAttribute('role', 'tablist');
```suggestion
    this.setAttribute('role', 'menu');
```

2022-03-08 17:55 UTC, blackfalcon commented on src/auro-menuoption.js
> +    this.setAttribute('role', 'tab');
```suggestion
    this.setAttribute('role', 'menuitem');
```

2022-03-08 17:55 UTC, blackfalcon commented on src/auro-menu.js
> +    this.addEventListener('click', this.makeSelection);
Using `click` only checks the option when the mouse click is up. This was discussed with the last iteration. 

```suggestion
    this.addEventListener('mousedown', this.makeSelection);
```

2022-03-08 17:55 UTC, blackfalcon commented on src/auro-menu.js
> +    option.ariaSelected = true;
Is the intention with the first load that the first element be selected if there isn't a defined pre-selected option? That's not a spec that I am aware of?

2022-03-08 18:00 UTC, jason-capsule42 commented on src/auro-menu.js
> +    this.setAttribute('role', 'tablist');
role `menu` is incompatible with `aria-selected="true"`. Either we need to ditch aria-selected or we need to change to a role combination that is supported.

This is outlined in the attached issues.

2022-03-08 18:00 UTC, jason-capsule42 commented on src/auro-menuoption.js
> +    this.setAttribute('role', 'tab');
See above comment about aria-selected.

2022-03-08 18:01 UTC, jason-capsule42 commented on src/auro-menu.js
> +    option.ariaSelected = true;
This is what was already happening in the existing code.

2022-03-08 18:06 UTC, geoffrich commented on src/auro-menu.js
> +    this.setAttribute('role', 'tablist');
I don't think `tablist` is an appropriate role here:

> The tablist role identifies the element that serves as the container for a set of tabs. The tab content are referred to as tabpanel elements.

Maybe this should be a [listbox](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/listbox_role) with [options](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/option_role)?

2022-03-08 18:13 UTC, blackfalcon commented on src/auro-menu.js
> +    this.setAttribute('role', 'tablist');
Yes, `listbox` and `option` seem like the right move here versus `tab` update.

2022-03-08 18:14 UTC, blackfalcon commented on src/auro-menu.js
> +    option.ariaSelected = true;
The previous version was only selecting the first option on an initial click event in a special case with an attribute. The current `main` branch does not do this on render. 

https://auro.alaskaair.com/components/auro/menu

2022-03-10 18:41 UTC, blackfalcon approved these changes

2022-03-10 22:57 UTC, merged